import { seoHead } from './seo.mjs';
import { releaseNotes } from './release-notes.mjs';
export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export function page(title, content) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)} | lvl222</title>${seoHead(title, escapeHtml)}<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/pages.css"><link rel="icon" href="/favicon.svg"></head><body><header class="header"><a href="/" class="wordmark">lvl<span>222</span><i></i></a><nav aria-label="Main navigation"><a href="/downloads">Downloads</a><a href="/support">Support</a><a class="discord-link" href="https://discord.gg/XRqY79PM8" target="_blank" rel="noopener noreferrer" aria-label="Join our Discord community (opens in a new tab)" title="Join our Discord community"><img src="/images/discord.svg" width="24" height="24" alt=""></a></nav></header><main class="wrap document"><h1>${escapeHtml(title)}</h1>${content}</main><footer class="wrap"><nav class="legal-nav" aria-label="Legal and support"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/license">Software license</a><a href="/source">Source code</a><a href="/support">Support</a></nav><p>Copyright (c) 2026 lvl222 and contributors. SC Companion is an independent fan project, not affiliated with the Cloud Imperium group of companies.</p></footer></body></html>`;
}
export const legalPages = {
  '/privacy': page('Privacy Policy', `<p>Effective September 9, 2026. This policy describes SC Companion and the lvl222.com website, operated by lvl222. Contact <a href="mailto:support@lvl222.com">support@lvl222.com</a> with privacy questions.</p>
  <h2>Information on your device</h2><p>The app stores settings, saved filters, cached third-party data, and read/unread state locally. If you use My RSI, the handle you enter and retrieved public profile information may be cached on your device. SC Companion does not ask for your RSI password; account-dashboard links open in your browser.</p>
  <h2>Optional gameplay logs</h2><p>When you configure local Game.log tracking, the app reads game logs and stores extracted events and session history locally. Logs may contain player handles, identifiers, locations, timestamps, file paths, and other technical or gameplay information. SC Companion does not automatically upload your gameplay logs or session history to lvl222. Be careful when sharing logs or screenshots in support requests.</p>
  <h2>Network requests and third parties</h2><p>Online features contact their data providers, including RSI/CIG, UEX Corp, and Star Citizen Wiki. Those providers receive network information such as your IP address and the request; profile and search features may send the handle or query you enter. External links, images, and media may contact other services, including YouTube. Their own privacy policies apply. These services are not controlled by lvl222.</p>
  <h2>Website, downloads, and updates</h2><p>The website does not add advertising trackers, analytics cookies, or user accounts. Website and installer requests are processed by our hosting provider, Vercel, including its Blob storage and delivery infrastructure. Hosting infrastructure may use technical cookies and record IP addresses, request URLs, timestamps, browser information, and errors for operation and security. The application does not send lvl222 an installation identifier or gameplay telemetry.</p><p>Direct-download editions may check for updates through GitHub or lvl222.com, depending on version. Microsoft Store editions use the Store for app updates. The relevant provider receives technical request information. Download requests do not establish how many distinct people installed or used the app.</p>
  <h2>Support and retention</h2><p>If you email support, we receive your address, message, and any attachments you choose to send. We use them to respond and investigate issues. Local app data remains until cleared or removed; uninstalling may leave data behind. Stop log tracking to stop further capture. Contact support for help locating local data or requesting deletion of information you sent us. Support records are kept while needed to handle the request and related operational or legal needs. Hosting-log retention is governed by the hosting service's settings and policies.</p>
  <h2>Your choices</h2><p>You can choose not to enable log tracking, disable notifications, stop background operation, and avoid features that contact external services. Depending on your location, you may have rights concerning personal information we hold. Email support@lvl222.com to make a request. Information already held by a third-party service must be addressed with that provider. We do not sell personal information or use it for targeted advertising.</p>
  <h2>Changes</h2><p>We will update this page and its effective date when our practices change.</p>`),
  '/terms': page('Terms and Notices', `<p>Effective September 9, 2026.</p><h2>Independent fan project</h2><p>SC Companion is developed by lvl222. It is not an official CIG application and is not affiliated with or endorsed by the Cloud Imperium group of companies.</p><h2>Information and estimates</h2><p>Third-party articles, listings, prices, stock levels, and specifications may be incomplete, delayed, or unavailable. Route profits and travel or cargo-handling times are estimates, not guarantees. The app does not broker marketplace transactions or guarantee sellers, buyers, or listings. Confirm important information with the original provider or in game.</p><h2>Software license</h2><p>The covered application software is licensed under GPL version 3. Your software rights and the applicable warranty provisions are set out in the <a href="/license">software license</a>. This page does not reduce rights granted by the GPL or rights that cannot be excluded under applicable law.</p><h2>Third-party content and trademarks</h2><p>Content not authored by lvl222 or contributors remains the property of its respective owners. Star Citizen, Roberts Space Industries, and Cloud Imperium are registered trademarks of Cloud Imperium Rights LLC. The app's software license does not grant rights to third-party content or trademarks. Data sources include <a href="https://robertsspaceindustries.com/">RSI/CIG</a>, <a href="https://uexcorp.space/">UEX Corp</a>, and <a href="https://star-citizen.wiki/">Star Citizen Wiki</a>.</p><h2>Contact</h2><p><a href="mailto:support@lvl222.com">support@lvl222.com</a></p>`),
  '/license': page('Software License', `<p>SC Companion's covered software is distributed under the GNU General Public License, version 3. Read the <a href="/licenses/gpl-3.0.txt">complete, unmodified GPL v3 license</a>.</p><p>The license governs your rights to run, copy, modify, and redistribute covered software and describes applicable warranty exclusions. Third-party libraries remain subject to their respective licenses. Third-party game content and trademarks are not relicensed by this notice.</p><p><a href="/source">Source code and build instructions</a></p><p>Copyright (c) 2026 lvl222 and contributors.</p>`),
  '/support': page('Support', `<p>For help with SC Companion or a privacy request, email <a href="mailto:support@lvl222.com">support@lvl222.com</a>.</p><p>For technical issues, include your operating system, app version, what you expected, and what happened. Remove personal information before attaching screenshots or logs. Never send account passwords, authentication codes, or payment information.</p><p><a href="/downloads">App downloads and release notes</a></p><p><a href="/privacy">Privacy policy</a></p>`)
};
export function downloadsPage(releases) {
  return page('SC Companion Downloads', `<a class="button primary store-button" href="https://apps.microsoft.com/store/detail/9P7MQG0CTW65?cid=DevShareMCLPCS" target="_blank" rel="noopener noreferrer"><span>Get it from Microsoft Store</span><span aria-hidden="true">↗</span></a><p>Windows and Linux installers are served directly from lvl222.com. Downloads are free. Windows installers are not Authenticode signed and may trigger SmartScreen. Microsoft Store users should get updates through the Store.</p>${!releases.length ? '<p>Installers are being prepared. Please try again shortly.</p>' : releases.map(r => `<section><h2>${escapeHtml(r.tag)}</h2><h3>What changed</h3>${releaseNotes[r.tag] ? `<ul class="release-changes">${releaseNotes[r.tag].map(note => `<li>${escapeHtml(note)}</li>`).join('')}</ul>` : `<p class="release-notes">${escapeHtml(r.notes || 'Release details have not yet been published.')}</p>`}<h3>Downloads</h3><ul class="file-list">${r.files.filter(f => !f.name.endsWith('.sig') && !f.name.endsWith('-source.zip')).map(f => `<li><a href="${escapeHtml(f.url)}">${escapeHtml(f.name)}</a><span>${(f.size / 1024 / 1024).toFixed(1)} MB</span></li>`).join('')}</ul><p><a href="/checksums#${escapeHtml(r.tag)}">File checksums and signatures</a> &middot; <a href="/source">Source code</a></p></section>`).join('')}`);
}
export function sourcePage(releases) {
  return page('Source Code', `<p>Source archives include the project's build instructions and software license. Match the source version to the installed app version.</p><ul>${releases.flatMap(r => r.files.filter(f => f.name.endsWith('-source.zip')).map(f => `<li><a href="${escapeHtml(f.url)}">${escapeHtml(f.name)}</a></li>`)).join('')}</ul><p>The development repository and Store-specific packaging history remain available on <a href="https://github.com/biged214/sccompanion">GitHub</a>. For corresponding source for a Store build or an older version not listed here, contact <a href="mailto:support@lvl222.com">support@lvl222.com</a>.</p><p><a href="/license">Software license</a></p>`);
}
export function checksumsPage(releases) {
  return page('Download Verification', `<p><a href="/downloads">Back to downloads and release notes</a></p><p>SHA-256 checksums are fingerprints of the published files. Comparing a downloaded file with its checksum helps detect corruption or a mismatch. A matching checksum alone does not prove a file is safe or identify its publisher. Most users can install normally; SC Companion's direct-download updater separately verifies signed updates.</p>${releases.map(r => `<section id="${escapeHtml(r.tag)}"><h2>${escapeHtml(r.tag)}</h2><ul class="file-list">${r.files.map(f => `<li><a href="${escapeHtml(f.url)}">${escapeHtml(f.name)}</a><span>${(f.size / 1024 / 1024).toFixed(1)} MB</span><code>${escapeHtml(f.sha256)}</code></li>`).join('')}</ul></section>`).join('')}`);
}
