import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
await mkdir(new URL('../public/images/', import.meta.url), { recursive: true });
const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
await page.goto('http://127.0.0.1:1421/');
await page.getByRole('button', { name: /Ships/ }).first().waitFor();
await page.screenshot({ path: 'public/images/home.png' });
await page.getByRole('button', { name: /Ships/ }).first().click();
await page.waitForTimeout(15000);
await page.evaluate(() => window.scrollTo(0, 0));
await page.waitForTimeout(500);
await page.screenshot({ path: 'public/images/ships.png' });
console.log((await page.locator('body').innerText()).slice(0, 2500));
await page.getByRole('button', { name: /Home/ }).first().click();
await page.getByRole('button', { name: /News/ }).first().click();
await page.waitForTimeout(10000);
await page.evaluate(() => window.scrollTo(0, 0));
await page.waitForTimeout(500);
await page.screenshot({ path: 'public/images/news.png' });
console.log((await page.locator('body').innerText()).slice(0, 1200));
await browser.close();
